import {
  collection,
  addDoc,
  Timestamp,
  getDocs,
  updateDoc,
  doc,
  deleteDoc,
  query,
  where,
} from 'firebase/firestore';
import { db } from '../firebase/config';
import {
  YouthApplication,
  AdultVolunteerApplication,
  Role,
  User,
  FormStatus,
  Branch,
} from '../types';

// Omit 'id' for creation, as it's generated by Firestore
type Creatable<T extends { id: string }> = Omit<T, 'id'>;

// SUBMIT_FUNCTIONS
export const submitYouthApplication = async (
  application: Omit<Creatable<YouthApplication>, 'timestamp' | 'status'>
) => {
  try {
    const docRef = await addDoc(collection(db, 'youth-applications'), {
      ...application,
      timestamp: Timestamp.now(),
      status: 'pending',
    });
    return docRef.id;
  } catch (error) {
    console.error('Error adding document: ', error);
    throw new Error('Failed to submit youth application');
  }
};

export const submitAdultVolunteerApplication = async (
  application: Omit<Creatable<AdultVolunteerApplication>, 'timestamp' | 'status'>
) => {
  try {
    const docRef = await addDoc(collection(db, 'adult-volunteer-applications'), {
      ...application,
      timestamp: Timestamp.now(),
      status: 'pending',
    });
    return docRef.id;
  } catch (error) {
    console.error('Error adding document: ', error);
    throw new Error('Failed to submit adult volunteer application');
  }
};

// FETCH_FUNCTIONS
export const getYouthApplications = async (branch?: Branch): Promise<YouthApplication[]> => {
  const applicationsCollection = collection(db, 'youth-applications');
  const q = branch ? query(applicationsCollection, where('branch', '==', branch)) : applicationsCollection;
  const snapshot = await getDocs(q);
  return snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() } as YouthApplication));
};

export const getAdultVolunteerApplications = async (): Promise<AdultVolunteerApplication[]> => {
  const snapshot = await getDocs(collection(db, 'adult-volunteer-applications'));
  return snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() } as AdultVolunteerApplication));
};

export const getAuthorizedEmails = async (): Promise<(User & { email: string })[]> => {
  const snapshot = await getDocs(collection(db, 'authorized-emails'));
  return snapshot.docs.map((doc) => ({ email: doc.id, ...doc.data() } as User & { email: string }));
};

// UPDATE_FUNCTIONS
export const updateApplicationStatus = async (
  applicationType: 'youth-applications' | 'adult-volunteer-applications',
  id: string,
  status: FormStatus
) => {
  const docRef = doc(db, applicationType, id);
  await updateDoc(docRef, { status });
};

// MANAGE_EMAILS_FUNCTIONS
export const addAuthorizedEmail = async (email: string, role: Role, branch?: Branch) => {
  const docRef = doc(db, 'authorized-emails', email);
  await addDoc(collection(db, 'authorized-emails'), {
    email,
    role,
    ...(branch && { branch }),
  });
};

export const removeAuthorizedEmail = async (email: string) => {
  const docRef = doc(db, 'authorized-emails', email);
  await deleteDoc(docRef);
};